# Generated by Django 6.1 on 2026-08-22
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(
            name='StudentIdSequence',
            fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('year', models.PositiveIntegerField(unique=True)), ('last_value', models.PositiveIntegerField(default=0))],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)), ('email_verified', models.BooleanField(default=False)),
                ('cnic', models.CharField(db_index=True, max_length=15, unique=True)), ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('phone', models.CharField(max_length=20)), ('father_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)), ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('nationality', models.CharField(blank=True, default='Pakistani', max_length=80)),
                ('student_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='auth.user')),
            ], options={'ordering': ['-created_at']},
        ),
    ]
