# Generated by Django 6.1 on 2026-08-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/%Y/%m/'),
        ),
    ]
