# Generated by Django 6.1 on 2026-08-22 09:21

import django.db.models.deletion
import students.models
import students.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('MATRIC', 'Matric Certificate/Result'), ('FSC', 'FSc/Intermediate Certificate/Result'), ('ENTRY_TEST', 'Entry Test Result'), ('CNIC_BFORM', 'CNIC/B-Form Copy'), ('OTHER', 'Other Supporting Document')], max_length=20)),
                ('file', models.FileField(upload_to=students.models.student_document_upload_path, validators=[students.validators.validate_academic_document])),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_documents', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'document_type'), name='one_document_per_type_per_student')],
            },
        ),
    ]
