# Generated by Django 6.1 on 2026-08-22 09:49

import django.core.validators
import django.db.models.deletion
import students.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_qualification_qualification_group_code'),
        ('students', '0003_academicdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=150)),
                ('group', models.CharField(choices=[('PRE_MEDICAL', 'Pre-Medical'), ('PRE_ENGINEERING', 'Pre-Engineering'), ('ICS', 'Intermediate in Computer Science (ICS)'), ('GENERAL_SCIENCE', 'General Science'), ('COMMERCE', 'Intermediate in Commerce (I.Com)'), ('HUMANITIES', 'Humanities / Arts'), ('OTHER', 'Other')], max_length=30)),
                ('passing_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)])),
                ('obtained_marks', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_record', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MatricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=100)),
                ('passing_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)])),
                ('obtained_marks', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matric_record', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('test_date', models.DateField()),
                ('result_certificate', models.FileField(blank=True, null=True, upload_to='test_score_certificates/%Y/', validators=[students.validators.validate_academic_document])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='students.studentprofile')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='admissions.testtype')),
            ],
            options={
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
