# Generated by Django 6.1 on 2026-08-22 05:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_academic_keys(apps, schema_editor):
    Campus = apps.get_model('admissions', 'Campus')
    Department = apps.get_model('admissions', 'Department')
    Program = apps.get_model('admissions', 'Program')

    for campus in Campus.objects.order_by('pk'):
        for department in Department.objects.filter(campus=campus).order_by('pk'):
            if not department.code:
                department.code = f'{campus.code}-{department.pk}'
                department.save(update_fields=['code'])
            Program.objects.filter(department=department, campus__isnull=True).update(campus=campus)


def clear_backfilled_academic_keys(apps, schema_editor):
    Department = apps.get_model('admissions', 'Department')
    Program = apps.get_model('admissions', 'Program')
    Program.objects.update(campus=None)
    Department.objects.update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='is_main_campus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='admissions.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='career_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate (Masters)', 'Graduate (Masters)'), ('Doctoral (PhD)', 'Doctoral (PhD)')], default='Undergraduate', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='required_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='admissions.qualification'),
        ),
        migrations.CreateModel(
            name='ProgramEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='admissions.program')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.qualification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('program', 'qualification'), name='unique_program_qualification')],
            },
        ),
        migrations.CreateModel(
            name='ProgramTestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alternative', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requirements', to='admissions.program')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.testtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('program', 'test_type'), name='unique_program_test_type')],
            },
        ),
        migrations.RunPython(backfill_academic_keys, clear_backfilled_academic_keys),
    ]
