# Generated by Django 6.1 on 2026-08-22 05:31

from django.db import migrations, models


def normalize_program_codes(apps, schema_editor):
    Program = apps.get_model('admissions', 'Program')
    seen = set()
    for program in Program.objects.select_related('campus', 'department__campus').order_by('pk'):
        code = program.code
        if code in seen:
            campus = program.campus or program.department.campus
            code = f'{code}-{campus.code}'
            if code in seen:
                code = f'{code}-{program.pk}'
            program.code = code[:30]
            program.save(update_fields=['code'])
        seen.add(program.code)


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_qualification_testtype_campus_is_main_campus_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_program_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
