# Generated by Django 6.1 on 2026-08-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_program_code'),
        ('students', '0003_academicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistapplicant',
            name='application_id',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='application_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SCHEDULED', 'Test Scheduled'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='eligibility_status',
            field=models.CharField(choices=[('PENDING', 'Pending Check'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='program_registration_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='qualifying_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='qualifying_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admissions.qualification'),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='RegistrationIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20)),
                ('admission_year_yy', models.CharField(max_length=2)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department_code', 'admission_year_yy'), name='unique_registration_sequence_scope')],
            },
        ),
    ]
