# Generated by Django 6.1 on 2026-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_pistapplicant_application_id_and_more'),
        ('students', '0003_academicdocument'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pistapplicant',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False), models.Q(('application_status', 'WITHDRAWN'), _negated=True)), fields=('student', 'program'), name='unique_active_student_program_application'),
        ),
    ]
