# Generated by Django 6.1 on 2026-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_pistapplicant_unique_active_student_program_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='qualification_group_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
