# Generated by Django 6.1 on 2026-08-22 10:25

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_qualification_qualification_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistapplicant',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.testsession'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='building',
            field=models.CharField(default='Academic Block A', max_length=200),
        ),
        migrations.AddField(
            model_name='testsession',
            name='hall',
            field=models.CharField(default='Hall 3', max_length=200),
        ),
        migrations.AddField(
            model_name='testsession',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.CreateModel(
            name='RollSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roll_slip', to='admissions.pistapplicant')),
                ('test_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roll_slips', to='admissions.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='RollNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campus', 'program', 'year'), name='unique_roll_sequence_scope')],
            },
        ),
    ]
