# Generated by Django 6.1 on 2026-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_pistapplicant_test_session_testsession_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcenter',
            name='city',
            field=models.CharField(default='Islamabad', max_length=120),
        ),
    ]
