# Generated by Django 6.1 on 2026-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_purge_lahore_karachi_campuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admissions.pistapplicant',),
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='application_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='fsc_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='fsc_total',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='matric_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='matric_total',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pistapplicant',
            name='source_application_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
