# Generated by Django 6.1 on 2026-08-21 09:11

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('admissions_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='admissions.campus')),
            ],
            options={
                'ordering': ['campus__city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PISTApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('cnic', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='applicants/photos/')),
                ('matric_marks', models.PositiveIntegerField()),
                ('matric_total', models.PositiveIntegerField()),
                ('fsc_marks', models.PositiveIntegerField()),
                ('fsc_total', models.PositiveIntegerField()),
                ('test_type', models.CharField(blank=True, choices=[('USAT', 'USAT'), ('MDCAT', 'MDCAT'), ('ECAT', 'ECAT'), ('NTS GAT', 'NTS GAT'), ('LAT', 'LAT'), ('Other', 'Other')], max_length=20)),
                ('test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('test_venue', models.CharField(blank=True, max_length=200)),
                ('test_building', models.CharField(blank=True, max_length=200)),
                ('test_hall', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Application Received', 'Application Received'), ('Roll No Issued', 'Roll No Issued'), ('Shortlisted for Entry Test', 'Shortlisted for Entry Test'), ('Merit List 1 Approved', 'Merit List 1 Approved'), ('Rejected', 'Rejected'), ('Eligibility Review', 'Eligibility Review'), ('Test Scheduled', 'Test Scheduled'), ('Test Appeared', 'Test Appeared'), ('Merit List 2', 'Merit List 2'), ('Selected', 'Selected'), ('Waitlisted', 'Waitlisted'), ('Admission Confirmed', 'Admission Confirmed')], default='Application Received', max_length=40)),
                ('source_application_id', models.CharField(db_index=True, max_length=80)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('passport_number', models.CharField(blank=True, max_length=40)),
                ('visa_information', models.CharField(blank=True, max_length=120)),
                ('international_address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admissions.campus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('USAT', 'USAT'), ('MDCAT', 'MDCAT'), ('ECAT', 'ECAT'), ('NTS GAT', 'NTS GAT'), ('LAT', 'LAT'), ('Other', 'Other')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='admissions.pistapplicant')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('code', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('eligibility_percentage', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('eligibility_text', models.TextField(blank=True)),
                ('required_test_type', models.CharField(choices=[('USAT', 'USAT'), ('MDCAT', 'MDCAT'), ('ECAT', 'ECAT'), ('NTS GAT', 'NTS GAT'), ('LAT', 'LAT'), ('Other', 'Other')], default='USAT', max_length=20)),
                ('admissions_open', models.BooleanField(default=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(default='4 Years', max_length=50)),
                ('degree_level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], default='Bachelor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.department')),
            ],
            options={
                'ordering': ['department__campus__city', 'department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pistapplicant',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admissions.program'),
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=200)),
                ('hall', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_centers', to='admissions.campus')),
            ],
            options={
                'ordering': ['campus__city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('reporting_time', models.TimeField(default=datetime.time(8, 30))),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='admissions.program')),
                ('test_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admissions.testcenter')),
            ],
            options={
                'ordering': ['test_date', 'reporting_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('campus', 'slug'), name='unique_department_slug_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='applicanttestscore',
            constraint=models.UniqueConstraint(fields=('applicant', 'test_type'), name='unique_applicant_test_type'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_program_code_per_department'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='unique_program_slug_per_department'),
        ),
        migrations.AddIndex(
            model_name='pistapplicant',
            index=models.Index(fields=['cnic'], name='admissions__cnic_4497e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pistapplicant',
            index=models.Index(fields=['email'], name='admissions__email_f90209_idx'),
        ),
        migrations.AddIndex(
            model_name='pistapplicant',
            index=models.Index(fields=['roll_number'], name='admissions__roll_nu_1c6062_idx'),
        ),
        migrations.AddIndex(
            model_name='pistapplicant',
            index=models.Index(fields=['status', 'created_at'], name='admissions__status_eef2ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='pistapplicant',
            constraint=models.UniqueConstraint(fields=('source_application_id', 'program'), name='unique_source_application_per_program'),
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.UniqueConstraint(fields=('test_center', 'program', 'test_date'), name='unique_session_per_center_program_date'),
        ),
    ]
